# Generated by Django 3.0.5 on 2020-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
